worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream gunicorn_app {
        server 127.0.0.1:8080;
        keepalive 32;
    }

    server {
        listen 80;
        server_name localhost;

        charset utf-8;

        location /public/ {
            alias "D:/IntelliJ IDEA/ProgEngineering/src/main/java/org/labs/lab2/public/";
            autoindex on;
        }

        location /gunicorn/ {
            proxy_pass http://gunicorn_app/generate;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}